### ISSUE TITLE
Need for a more detailed documentation

### ISSUE THREAD

**Issue by gevera** [crbelaus/bun#15]
After reading thoroughly the README and going along with it, I still struggle to make Bun work with Phoenix.

Couple of questions to consider:

1.  What to do with esbuild? Should it run along Bun? Or maybe it should be removed?
2.  After implementing Bun in Phoenix, what's next? How do I do write my frontend with Bun? 

Thank you

**Comment by crbelaus** [comment]
Both of your questions are answered in [bun's documentation](https://bun.sh/docs). This package is just an installer so you can easily download and run bun from your Elixir projects.
