### ISSUE TITLE
Document how to replace the default Phoenix stack with just Bun

### ISSUE THREAD

**Issue by crbelaus** [crbelaus/bun#22]
A great idea was shared on #20 that consists on replacing the default Phoenix stack (esbuild + tailwind packages) with just Bun.

This makes a lot of sense and I believe would be a great addition to the documentation. We could have a section dedicated to how to make this change and how to configure `bun build` as an esbuild replacement and `bun run tailwind` as a tailwind replacement.

**Comment by D4no0** [comment]
Indeed, one more addition you could do is to look into [igniter](https://hexdocs.pm/igniter/readme.html). With some effort the `phx.new` could be refactored into a fully configurable generator that would allow easy replacement of the build system.

**Comment by crbelaus** [comment]
This has been fixed in #23. The igniter suggestion is great and I will most likely try to write an installer at some point.
