### ISSUE TITLE
Using Bun to run arbitrary Javascript code from Elixir

### ISSUE THREAD

**Issue by woutdp** [crbelaus/bun#24]
For the [LiveSvelte](https://github.com/woutdp/live_svelte) project I'm currently using [nodejs](https://github.com/revelrylabs/elixir-nodejs) to SSR Svelte from within Elixir.

The api for this is something like (you can see the code here https://github.com/woutdp/live_svelte/blob/master/lib/ssr/node_js.ex):

```elixir
NodeJS.call!({"server", "render"}, [name, props, slots], binary: true)
```

`"server"` is the name of the `server.js` file which defines how to render something. 
`"render"` is the function name
`[name, props, slots]` are my function arguments
`binary` handles unicode characters properly

I would like to do something similar with Bun. The API doesn't need to be the same.

I've looked into `bun.run/2` but it seems it only allows me to specify a file or command to run, which would not be sufficient as I need to also specify a function and function arguments.

Am I overlooking something and is this something that's already supported? If not, have you considered adding it and if not, would you be open for a PR to add this?

Also I'm noticing that your package uses ports to call to executables. `nodejs` uses a supervisor which starts a node process. That might be a bit faster than using ports but I haven't benchmarked it.

Also if this is not in the scope of the package please let me know :)

**Comment by crbelaus** [comment]
This package is meant to provide a Bun installer with the same spirit of [Esbuild](https://github.com/phoenixframework/esbuild).

Yours is an interesting idea, but it falls out of the scope of this project.

**Comment by woutdp** [comment]
Hi @crbelaus thank you for the quick reply! Understood, great project btw!

**Comment by andresgutgon** [comment]
I came looking for the same, do you know if this exists? 

I think it could be a killer feature to run inertia projects on ssr mode and get that nice performance from Bun
