### ISSUE TITLE
`:zip.unzip/2` now returns directory name too in Erlang 27.1

### ISSUE THREAD

**Issue by natrys** [crbelaus/bun#25]
The [changelog](https://www.erlang.org/patches/otp-27.1) only mentions this about `:zip.list_dir/2`, but I am seeing the effect for `:zip.unzip/2` too.

So here:

https://github.com/crbelaus/bun/blob/75aa6556ee45775b6134ee836b6d2f29da42ea3e/lib/bun.ex#L208-L212

Before `download_path` was say `[~c"/tmp/bun-linux-x64/bun"]`, now its `[~c"/tmp/bun-linux-x64/", ~c"/tmp/bun-linux-x64/bun"]`. This is now failing in `File.cp!` later (as an aside, it's not because it got wrong type, but apparently for anything that expects chardata but is given something else, elixir attempts implicit conversion which for list means joining everything which produces nonsense path here, this just happened to be not a problem with one element list).

Another arm in the case pattern should fix it in backward compatible way I guess, lmk if you want me to create PR.

**Comment by crbelaus** [comment]
Thanks for the heads up @natrys. This should be fixed on #26
