### ISSUE TITLE
`:zip.unzip/2` returning longer list of paths

### ISSUE THREAD

**Issue by gianpispi** [crbelaus/bun#28]
In reference to #25, i'm on Erlang 27.2 on macOS, and I get a longer list of paths here:

https://github.com/crbelaus/bun/blob/b82e8801281d983ad04d5d82a3180765c7a79be1/lib/bun.ex#L226-L231

I get this:
```elixir
{:ok, [~c"/tmp/bun-darwin-aarch64/", ~c"/tmp/bun-darwin-aarch64/bun", ~c"/tmp/__MACOSX/", ~c"/tmp/__MACOSX/bun-darwin-aarch64/", ~c"/tmp/__MACOSX/bun-darwin-aarch64/._bun"]}
```

something like this would probably work:
```elixir
case :zip.unzip(zip, cwd: to_charlist(tmp_dir)) do 
   {:ok, [download_path]} -> download_path 
   # OTP 27.1 and newer versions return both the unzipped folder and file 
   {:ok, [_download_folder, download_path]} -> download_path 
   {:ok, [_download_folder, download_path | _]} -> download_path 
   other -> raise "couldn't unpack archive: #{inspect(other)}" 
end
```

**Comment by crbelaus** [comment]
Let me take a look at this. I've also had some surprising behaviour changes in the `:zip` module on OTP 27.2 in my day job.

**Comment by crbelaus** [comment]
@gianpispi can you share which Bun version are you trying to install? I want to check the zip out in case it contains more files.

**Comment by gianpispi** [comment]
@crbelaus I'm trying with v`1.1.42`

**Comment by crbelaus** [comment]
Looks like the zip archive contains multiple files and directories:

```
➜  ~/Documents unzip bun-darwin-aarch64.zip
Archive:  bun-darwin-aarch64.zip
   creating: bun-darwin-aarch64/
  inflating: bun-darwin-aarch64/bun
   creating: __MACOSX/
   creating: __MACOSX/bun-darwin-aarch64/
  inflating: __MACOSX/bun-darwin-aarch64/._bun
```

**Comment by crbelaus** [comment]
This should be fixed on #29.

Can you try that branch and confirm if it works for you @gianpispi?

**Comment by gianpispi** [comment]
@crbelaus yup, working now. thank you, and happy holidays!

**Comment by crbelaus** [comment]
#29 is now merged with this fix. I will publish a new release shortly.

**Comment by crbelaus** [comment]
Bun [1.4.1](https://github.com/crbelaus/bun/releases/tag/v1.4.1) is now published with this fix.
